export default strings = {
  usernameLabel: "Email or Username",
  passwordLabel: "Password",
  forgotLabel: "Forgot password?",
  loginButton: "LOGIN",
  nextStep: "Next",
  registerLabel: "Create account",
  registerUsername: "Username *",
  registerEmail: "Email *",
  registerPassword: "Password *",
  registerRepeatPassword: "Repeat password *",
  registerPhone: "Phone  (Optional)",
  logout: "Logout",
  send: "Send",

  brandSelectTitle: "Select brand",
  modelSelectTitle: "Select model",
  finalPreviewTitle: "Preview",

  nextInspect: "Incoming revisions",
  noInspections: "No inspections",

  years: "years",
  year: "year",
  months: "months",
  month: "month",
  days: "days",
  day: "day",
  hours: "hours",
  hour: "hour",
  minutes: "minutes",
  minute: "minute",
  seconds: "seconds",
  or: "or",

  previewName: "Name *",
  errorPreviewName: "Name required",
  addBikeButton: "Add bike",
  newRevisionButton: "+",

  labelName: "Name:",
  newBike: "New bike",
};
