export default strings = {
  usernameLabel: "Email or Username",
  passwordLabel: "Password",
  forgotLabel: "Forgot password?",
  loginButton: "LOGIN",
  nextStep: "Next",
  registerLabel: "Create account",
  registerUsername: "Username *",
  registerEmail: "Email *",
  registerPassword: "Password *",
  registerRepeatPassword: "Repeat password *",
  registerPhone: "Phone  (Optional)",
  logout: "Logout",
  send: "Send",

  brandSelectTitle: "Select brand",
  modelSelectTitle: "Select model",
  finalPreviewTitle: "Preview",
  editBikeTitle: "Edit",

  nextInspect: "Incoming revisions",
  noInspections: "No inspections",
  inspections: "Inspections:",
  revisions: "Revisions",

  years: "years",
  year: "year",
  months: "months",
  month: "month",
  days: "days",
  day: "day",
  hours: "hours",
  hour: "hour",
  minutes: "minutes",
  minute: "minute",
  seconds: "seconds",
  or: "or",

  previewName: "Name *",
  errorPreviewName: "Name required",
  addBikeButton: "Add bike",
  deleteBikeButton: "Delete",
  editBikeButton: "Save",
  newRevisionButton: "+",

  labelName: "Name:",
  labelDistPerYear: "Distance per year:",
  labelTotalDistance: "Total distance traveled:",
  newBike: "New bike",
  km: "Km",
  pendingRevision: "Pending...",
  labelTotal: "Total:",
  notifications: "Notifications",

  alertEditTitle: "Do you want to save?",
  alertEditText: "Some inspections have been modified",

  alertDeleteBikeTitle: (name) => `Delete ${name || "bike"}?`,
  alertDeleteBikeText: "This action is irreversible.",

  editUserButton: "Save",
  editPasswordButton: "Change pasword",
  oldPassword: "Current password *",
  newPassword: "New password *",

  send: "Send",
  code: "Code",
  check: "Check",
};
